// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV6pScpMLcu69Jo4eMqSAgh_pY8b1Ql2w',
    appId: '1:533080583769:web:167f1275665cba29fc4b48',
    messagingSenderId: '533080583769',
    projectId: 'graduation-project-560f4',
    authDomain: 'graduation-project-560f4.firebaseapp.com',
    storageBucket: 'graduation-project-560f4.appspot.com',
    measurementId: 'G-ZWFEHLBKMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFVQaMeYx45P7EAWcyI1doRyKTKeKyJhM',
    appId: '1:533080583769:android:a007d86899676723fc4b48',
    messagingSenderId: '533080583769',
    projectId: 'graduation-project-560f4',
    storageBucket: 'graduation-project-560f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdNTc0EFL5dR6J02Tnr-cfK7JLhiB3eUg',
    appId: '1:533080583769:ios:dd8ef16bbec781aefc4b48',
    messagingSenderId: '533080583769',
    projectId: 'graduation-project-560f4',
    storageBucket: 'graduation-project-560f4.appspot.com',
    iosBundleId: 'com.example.cleanHouse',
  );
}
